CREATE TABLE RESERVE
(
	CFMNUMBER INT,
	NAME VARCHAR2(100),
	ROOMNUMBER INT UNIQUE
)

DROP TABLE RESERVE

ALTER TABLE RESERVE
	DROP FOREIGN KEY


ALTER TABLE RESERVE
	ADD CONSTRAINT RESERVE_CFMNUMBER_PK PRIMARY KEY(CFMNUMBER)
	

ALTER TABLE RESERVE
	ADD CONSTRAINT RESERVE_ROOMNUMBER_FK FOREIGN KEY(ROOMNUMBER)
	REFERENCES HOTEL(ROOMNUMBER)
	

SELECT * FROM RESERVE

CREATE SEQUENCE NO_SEQ
DROP SEQUENCE NO_SEQ

DELETE FROM RESERVE WHERE CFMNUMBER = 1


INSERT INTO RESERVE VALUES(NO_SEQ.NEXTVAL, 'ASD', 101)

-- 전체 숙박현황조회
CREATE OR REPLACE VIEW CURRENT_ROOMS
AS
SELECT H.ROOMNUMBER, H.ROOMGRADE, H.ROOMPRICE,NVL(R.CFMNUMBER,0) AS CFMNUMBER, NVL(R.NAME,' ')AS NAME
FROM HOTEL H LEFT OUTER JOIN RESERVE R
ON H.ROOMNUMBER = R.ROOMNUMBER
ORDER BY H.ROOMNUMBER


-- 숙박 가능한 방 조회
CREATE OR REPLACE VIEW AVAILABLE_ROOMS
AS
SELECT H.ROOMNUMBER, H.ROOMGRADE, H.ROOMPRICE
FROM HOTEL H LEFT OUTER JOIN RESERVE R
ON H.ROOMNUMBER = R.ROOMNUMBER
WHERE R.CFMNUMBER IS NULL
ORDER BY H.ROOMNUMBER


